name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Execute notebooks
      run: |
        jupyter nbconvert --to notebook --execute notebooks/01_data_exploration.ipynb
        jupyter nbconvert --to notebook --execute notebooks/02_data_cleaning.ipynb  
        jupyter nbconvert --to notebook --execute notebooks/03_funnel_analysis.ipynb
        jupyter nbconvert --to notebook --execute notebooks/04_channel_optimization.ipynb
        jupyter nbconvert --to notebook --execute notebooks/05_statistical_modeling.ipynb
    
    - name: Convert notebooks to HTML
      run: |
        jupyter nbconvert --to html notebooks/01_data_exploration.ipynb --output-dir=docs/notebooks
        jupyter nbconvert --to html notebooks/02_data_cleaning.ipynb --output-dir=docs/notebooks
        jupyter nbconvert --to html notebooks/03_funnel_analysis.ipynb --output-dir=docs/notebooks
        jupyter nbconvert --to html notebooks/04_channel_optimization.ipynb --output-dir=docs/notebooks
        jupyter nbconvert --to html notebooks/05_statistical_modeling.ipynb --output-dir=docs/notebooks
    
    - name: Create docs directory structure
      run: |
        mkdir -p docs
        cp index.html docs/
        cp case_study_responses.md docs/
        cp -r data docs/ || true
        cp -r assets docs/ || true
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        publish_branch: gh-pages